module mod_vdc
  use mod_f90_kind
  implicit none
  ! DC voltage generated by oscillatory electric field for each plane
  ! (1 - AMR, 2 - AHE, 3 - PHE)
  real(double),dimension(:,:),allocatable :: vdc
  real(double),dimension(:)  ,allocatable :: total_vdc
contains

  ! This subroutine allocates variables related to V_dc calculation
  subroutine allocate_vdc()
    use mod_f90_kind
    use mod_mpi_pars
    use mod_parameters, only: Npl,outputunit
    implicit none
    integer           :: AllocateStatus

    if(myrank_row.eq.0) then
      allocate( vdc(3,Npl),total_vdc(3), STAT = AllocateStatus )
      if (AllocateStatus.ne.0) then
        write(outputunit,"('[allocate_vdc] Not enough memory for: vdc,total_vdc')")
        call MPI_Abort(MPI_COMM_WORLD,errorcode,ierr)
      end if
    end if

    return
  end subroutine allocate_vdc

  ! This subroutine deallocates variables related to V_dc calculation
  subroutine deallocate_vdc()
    use mod_f90_kind
    use mod_mpi_pars
    implicit none

    if(myrank_row.eq.0) then
      deallocate(vdc,total_vdc)
    end if

    return
  end subroutine deallocate_vdc

  ! This subroutine opens and closes all the files needed for V_dc
  subroutine openclose_vdc_files(iflag)
    use mod_parameters
    use mod_mpi_pars
    implicit none

    character(len=500)  :: varm
    character(len=50)   :: fieldpart,socpart
    character(len=7)    :: folder
    character(len=4)    :: filename,effect(3)
    character(len=1)    :: SOCc
    integer :: i,sigma,iw,iflag,err,errt=0

    fieldpart = ""
    socpart   = ""
    if(SOC) then
      if(llinearsoc) then
        SOCc = "L"
      else
        SOCc = "T"
      end if
      write(socpart,"('_magaxis=',a,'_socscale=',f5.2)") magaxis,socscale
    else
      SOCc = "F"
    end if
    if(lfield) then
      write(fieldpart,"('_hwa=',es9.2,'_hwt=',f5.2,'_hwp=',f5.2)") hw_list(hw_count,1),hw_list(hw_count,2),hw_list(hw_count,3)
      if(ltesla)    fieldpart = trim(fieldpart) // "_tesla"
      if(lnolb)     fieldpart = trim(fieldpart) // "_nolb"
      if(lhwscale)  fieldpart = trim(fieldpart) // "_hwscale"
      if(lhwrotate) fieldpart = trim(fieldpart) // "_hwrotate"
    end if

    folder = "Vdc"
    if(lhfresponses) folder = trim(folder) // "_HF"
    filename = "Vdc"

    effect(1) = "_AMR"
    effect(2) = "_AHE"
    effect(3) = "_PHE"

    if(iflag.eq.0) then
      do sigma=1,3 ; do i=1,Npl
        iw = 10000+(sigma-1)*Npl+i
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,'_pos=',i0,'_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(filename),effect(sigma),i,parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='unknown', form='formatted')
        write(unit=iw, fmt="('#     energy    , ',a,a)") trim(filename),effect(sigma)
        close(unit=iw)
      end do ; end do
      do sigma=1,3
        iw = 11000+sigma
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,'_total_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(filename),effect(sigma),parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='unknown', form='formatted')
        write(unit=iw, fmt="('#     energy    , ',a,a)") trim(filename),effect(sigma)
        close(unit=iw)
      end do
    else if (iflag.eq.1) then
      do sigma=1,3 ; do i=1,Npl
        iw = 10000+(sigma-1)*Npl+i
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,'_pos=',i0,'_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(filename),effect(sigma),i,parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='old', position='append', form='formatted', iostat=err)
        errt = errt + err
      end do ; end do
      do sigma=1,3
        iw = 11000+sigma
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,'_total_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(filename),effect(sigma),parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='old', position='append', form='formatted', iostat=err)
        errt = errt + err
      end do
      ! Stop if some file does not exist
      if(errt.ne.0) then
        write(outputunit,"(a,i0,a)") "[openclose_vdc_files] Some file(s) do(es) not exist! Stopping before starting calculations..."
        call MPI_Abort(MPI_COMM_WORLD,errorcode,ierr)
      end if
    else
      do sigma=1,3 ; do i=1,Npl
        iw = 10000+(sigma-1)*Npl+i
        close(unit=iw)
      end do ; end do
      do sigma=1,3
        iw = 11000+sigma
        close(unit=iw)
      end do
    end if

    return
  end subroutine openclose_vdc_files

  ! This subroutine write all V_dc into files
  ! (already opened with openclose_vdc_files(1))
  ! Some information may also be written on the screen
  subroutine write_vdc(e)
    use mod_f90_kind
    use mod_parameters, only: Npl
    implicit none
    integer  :: i,iw,sigma
    real(double),intent(in) :: e

    do sigma=1,3 ; do i=1,Npl
      iw = 10000+(sigma-1)*Npl+i

      write(unit=iw,fmt="(2(es16.9,2x))") e , vdc(sigma,i)
    end do ; end do
    do sigma=1,3
      iw = 11000+sigma

      write(unit=iw,fmt="(2(es16.9,2x))") e , total_vdc(sigma)
    end do

    return
  end subroutine write_vdc

  ! This subroutine opens and closes all the files needed for V_dc in the dc limit/fixed frequency
  subroutine openclose_dc_vdc_files(iflag)
    use mod_parameters
    use mod_mpi_pars
    implicit none

    character(len=500)  :: varm
    character(len=50)   :: fieldpart,socpart
    character(len=7)    :: folder
    character(len=4)    :: filename,effect(3)
    character(len=1)    :: SOCc
    integer :: i,sigma,iw,iflag,err,errt=0

    fieldpart = ""
    socpart   = ""
    if(SOC) then
      if(llinearsoc) then
        SOCc = "L"
      else
        SOCc = "T"
      end if
      write(socpart,"('_magaxis=',a,'_socscale=',f5.2)") magaxis,socscale
    else
      SOCc = "F"
    end if

    if(dcfield_dependence.ne.7) then
      if((dcfield_dependence.ne.1).and.(dcfield_dependence.ne.4).and.(dcfield_dependence.ne.5)) write(fieldpart,"(a,'_hwa=',es9.2)") trim(fieldpart),hwa
      if((dcfield_dependence.ne.2).and.(dcfield_dependence.ne.4).and.(dcfield_dependence.ne.6)) write(fieldpart,"(a,'_hwt=',f5.2)") trim(fieldpart),hwt
      if((dcfield_dependence.ne.3).and.(dcfield_dependence.ne.5).and.(dcfield_dependence.ne.6)) write(fieldpart,"(a,'_hwp=',f5.2)") trim(fieldpart),hwp
    end if
    if(ltesla)    fieldpart = trim(fieldpart) // "_tesla"
    if(lnolb)     fieldpart = trim(fieldpart) // "_nolb"
    if(lhwscale)  fieldpart = trim(fieldpart) // "_hwscale"
    if(lhwrotate) fieldpart = trim(fieldpart) // "_hwrotate"

    folder = "Vdc"
    if(lhfresponses) folder = trim(folder) // "_HF"
    filename = "Vdc"

    effect(1) = "_AMR"
    effect(2) = "_AHE"
    effect(3) = "_PHE"

    if(iflag.eq.0) then
      do sigma=1,3 ; do i=1,Npl
        iw = 100000+(sigma-1)*Npl+i
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,a,'_',a,'_pos=',i0,'_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(dcprefix(count)),trim(filename),effect(sigma),trim(dcfield(dcfield_dependence)),i,parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='unknown', form='formatted')
        write(unit=iw, fmt="('#',a,'  ',a,a,'  , mag angle theta , mag angle phi  ')") trim(dc_header),trim(filename),effect(sigma)
        close(unit=iw)
      end do ; end do
      do sigma=1,3
        iw = 110000+sigma
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,a,'_',a,'_total_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(dcprefix(count)),trim(filename),effect(sigma),trim(dcfield(dcfield_dependence)),parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='unknown', form='formatted')
        write(unit=iw, fmt="('#',a,'  ',a,a,'  , mag angle theta , mag angle phi  ')") trim(dc_header),trim(filename),effect(sigma)
        close(unit=iw)
      end do
    else if (iflag.eq.1) then
      do sigma=1,3 ; do i=1,Npl
        iw = 100000+(sigma-1)*Npl+i
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,a,'_',a,'_pos=',i0,'_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(dcprefix(count)),trim(filename),effect(sigma),trim(dcfield(dcfield_dependence)),i,parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='old', position='append', form='formatted', iostat=err)
        errt = errt + err
      end do ; end do
      do sigma=1,3
        iw = 110000+sigma
        write(varm,"('./results/',a1,'SOC/',a,'/',a,'/',a,a,a,'_',a,'_total_parts=',i0,'_parts3=',i0,'_ncp=',i0,'_eta=',es8.1,'_Utype=',i0,a,a,'_dirEfield=',a,a,'.dat')") SOCc,trim(Npl_folder),trim(folder),trim(dcprefix(count)),trim(filename),effect(sigma),trim(dcfield(dcfield_dependence)),parts,parts3,ncp,eta,Utype,trim(fieldpart),trim(socpart),dirEfield,trim(suffix)
        open (unit=iw, file=varm, status='old', position='append', form='formatted', iostat=err)
        errt = errt + err
      end do
      ! Stop if some file does not exist
      if(errt.ne.0) then
        write(outputunit,"(a,i0,a)") "[openclose_dc_vdc_files] Some file(s) do(es) not exist! Stopping before starting calculations..."
        call MPI_Abort(MPI_COMM_WORLD,errorcode,ierr)
      end if
    else
      do sigma=1,3 ; do i=1,Npl
        iw = 100000+(sigma-1)*Npl+i
        close(unit=iw)
      end do ; end do
      do sigma=1,3
        iw = 110000+sigma
        close(unit=iw)
      end do
    end if

    return
  end subroutine openclose_dc_vdc_files

  ! This subroutine write all V_dc into files
  ! (already opened with openclose_dc_vdc_files(1))
  ! Some information may also be written on the screen
  subroutine write_dc_vdc()
    use mod_f90_kind
    use mod_parameters, only: Npl,dc_fields,hw_count,mmlayermag
    use mod_magnet, only: mvec_spherical
    implicit none
    integer  :: i,iw,sigma

    do sigma=1,3 ; do i=1,Npl
      iw = 100000+(sigma-1)*Npl+i

      write(unit=iw,fmt="(a,2x,3(es16.9,2x))") trim(dc_fields(hw_count)) , vdc(sigma,i) , mvec_spherical(i,2) , mvec_spherical(i,3)
    end do ; end do

    do sigma=1,3
      iw = 110000+sigma

      write(unit=iw,fmt="(a,2x,3(es16.9,2x))") trim(dc_fields(hw_count)) , total_vdc(sigma) , mvec_spherical(mmlayermag(1)-1,2) , mvec_spherical(mmlayermag(1)-1,3)
    end do

    return
  end subroutine write_dc_vdc

  ! This subroutine sorts V_dc files
  subroutine sort_vdc()
    use mod_f90_kind
    use mod_parameters, only: Npl,itype
    use mod_tools, only: sort_file
    implicit none
    integer :: i,sigma,iw,idc=1

    ! Opening V_dc files
    if(itype.eq.9) then
      idc=10
      call openclose_dc_vdc_files(1)
    else
      call openclose_vdc_files(1)
    end if

    do sigma=1,3 ; do i=1,Npl
      iw = 10000*idc+(sigma-1)*Npl+i
      ! Sorting V_dc files
      call sort_file(iw,.true.)
    end do ; end do
    do sigma=1,3
      iw = 11000*idc+sigma
      ! Sorting total V_dc files
      call sort_file(iw,.true.)
    end do

    ! Closing V_dc files
    if(itype.eq.9) then
      call openclose_dc_vdc_files(2)
    else
      call openclose_vdc_files(2)
    end if

    return
  end subroutine sort_vdc

end module mod_vdc